### ISSUE TITLE
Doesn't respect autoplay, mute, loop, or controls options from videojs

### ISSUE THREAD

**Issue by jaspax** [hola/hola_player#2]
A <video> tag controlled with hola_player doesn't respect the autoplay, mute, loop, or controls options. Test by going to http://hola.github.io/examples/cdn/#hola_player, add any of those attributes to the video tag. None of them have any affect on the output.

**Comment by bahaa-aidi** [comment]
Fixed in version 1.0.1
Please note that the attribute is 'muted' not 'mute'.
Also note that [hola/videojs5-settings](https://github.com/hola/videojs5-settings) plugin, which is enabled by default, restores last volume level/mute from localStorage, you can disable this persistent volume like this: `hola_player({volume: false})`

**Comment by jaspax** [comment]
Confirmed fixed in 1.0.1
